version: '3'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
